# Generated by Django 4.2.5 on 2024-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="File path"
            ),
        ),
    ]
