# Generated by Django 4.2.5 on 2024-03-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_rename_creation_updated_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmwork",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="modified_at",
            new_name="updated_at",
        ),
    ]
