# Generated by Django 4.2.5 on 2024-03-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_rename_updated_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="created",
            new_name="created_at",
        ),
    ]
