# Generated by Django 4.2.5 on 2024-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_rename_updated_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[("PR", "Producer"), ("AC", "Actor"), ("DR", "Director"), ("WR", "Writer")],
                default="AC",
                max_length=2,
                verbose_name="role",
            ),
        )
    ]
